name: Docker Image Test1

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push the Docker image
      run:  |
        echo "${{ secrets.Dockerhubpw }}" | docker login  -u "neeleshdeva"  --password-stdin 
        docker image build -t neeleshdeva/githubimagepush:01v1 .
        docker push neeleshdeva/githubimagepush:01v1
              
      
