on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  Build-Code:
    name: Building the Complete Code
    runs-on: ubuntu-latest
  #  container: node:17.6.0
    steps:
    - uses: actions/checkout@v3
    - name: Build and push the Docker image
      run:  |
        echo "${{ secrets.Dockerhubpw }}" | docker login  -u "neeleshdeva"  --password-stdin 
        docker image build -t neeleshdeva/githubimagepush:01v1 .
        docker push neeleshdeva/githubimagepush:01v1
      
  Release-Projects:
    name: Create Release
    runs-on: ubuntu-latest
  #  container: node:17.6.0
    needs: Build-Code
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Github Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      
      
      
      
      
